#plus <- read.table('di_plus_mRNA_LiHe_41_Hf03.txt')
#minus <- read.table('di_minus_mRNA_LiHe_41_Hf03.txt')
args <- commandArgs(trailingOnly=T)
plus <- read.table(args[1])
minus <- read.table(args[2])
ens <- read.table('/MMCI/MS/DEEP-liver/work/Preprocessing/references/gencode.v19.annotation_trimmed.gtf')
match <- sapply(seq(nrow(plus)),function(i)which(as.character(plus[i,1])==as.character(ens[,6]))[1])
match.minus <- sapply(seq(nrow(minus)),function(i)which(as.character(minus[i,1])==as.character(ens[,6]))[1])
pp <- which(as.character(ens[match,8])=='protein_coding'&as.character(ens[match.minus,8])=='protein_coding')
np <- which(as.character(ens[match,8])=='protein_coding'&as.character(ens[match.minus,8])!='protein_coding')
pn <- which(as.character(ens[match,8])!='protein_coding'&as.character(ens[match.minus,8])=='protein_coding')
nn <- which(as.character(ens[match,8])!='protein_coding'&as.character(ens[match.minus,8])!='protein_coding')
write.table(plus[pp,],'PP_plus.txt',quote=F,row.names=F,col.names=F);write.table(minus[pp,],'PP_minus.txt',quote=F,row.names=F,col.names=F)
write.table(plus[pn,],'PN_plus.txt',quote=F,row.names=F,col.names=F);write.table(minus[pn,],'PN_minus.txt',quote=F,row.names=F,col.names=F)
write.table(plus[np,],'NP_plus.txt',quote=F,row.names=F,col.names=F);write.table(minus[np,],'NP_minus.txt',quote=F,row.names=F,col.names=F)
write.table(plus[nn,],'NN_plus.txt',quote=F,row.names=F,col.names=F);write.table(minus[nn,],'NN_minus.txt',quote=F,row.names=F,col.names=F)

